services:
  backend:
    build: ./backend
    # image: abhishekganji27/docker-swarm-dashboard
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  frontend:
    
    build: ./frontend
    
    ports:
      - "5173:80"

    deploy:
      placement:
        constraints:
          - "node.role==manager"